// examples/react-counter/src/main.tsx
import { createRoot } from "react-dom/client";

import { createApp, defineModule } from "@coexist/core";
import { CoexistProvider, useModule, useSelector } from "@coexist/react";

// oxlint-disable-next-line import/no-unassigned-import -- Vite loads example styles through CSS side effects.
import "./styles.css";

class Counter {
  count = 0;

  get double(): number {
    return this.count * 2;
  }

  increase(step = 1): void {
    this.count += step;
  }

  reset(): void {
    this.count = 0;
  }
}

defineModule(Counter, {
  actions: ["increase", "reset"],
  computed: ["double"],
  name: "counter",
  state: ["count"],
});

const app = createApp({
  providers: [Counter],
});

function CounterView() {
  const counter = useModule(Counter);
  const count = useSelector(Counter, (module) => module.count);
  const double = useSelector(Counter, (module) => module.double);

  return (
    <main className="shell">
      <section className="panel">
        <span className="eyebrow">React + Coexist</span>
        <h1>Counter module</h1>
        <dl className="stats">
          <div>
            <dt>Count</dt>
            <dd>{count}</dd>
          </div>
          <div>
            <dt>Double</dt>
            <dd>{double}</dd>
          </div>
        </dl>
        <div className="actions">
          <button type="button" onClick={() => counter.increase()}>
            Increase
          </button>
          <button type="button" className="secondary" onClick={() => counter.reset()}>
            Reset
          </button>
        </div>
      </section>
    </main>
  );
}

createRoot(document.getElementById("root")!).render(
  <CoexistProvider app={app}>
    <CounterView />
  </CoexistProvider>,
);

// examples/inventory-workbench/src/main.tsx
import { createRoot } from "react-dom/client";
import { createApp as createVueApp } from "vue";

import { CoexistProvider } from "@coexist/react";
import { coexistPlugin } from "@coexist/vue";

import { SeedCatalogGateway } from "./catalog";
import { createWorkerPlanner } from "./planner";
import { ReactPanel } from "./ReactPanel";
import VuePanel from "./VuePanel.vue";
import { createWorkbench } from "./workbench";

// oxlint-disable-next-line import/no-unassigned-import -- Vite loads example styles through CSS side effects.
import "./styles.css";

const catalog = new SeedCatalogGateway();
const workerPlanner = await createWorkerPlanner();
const { app } = createWorkbench({
  catalog,
  planner: workerPlanner.planner,
  disposePlanner: workerPlanner.dispose,
});

await app.ready;

const reactRoot = createRoot(document.getElementById("react-root")!);
reactRoot.render(
  <CoexistProvider app={app}>
    <ReactPanel catalog={catalog} />
  </CoexistProvider>,
);

const vueRoot = createVueApp(VuePanel);
vueRoot.use(coexistPlugin(app));
vueRoot.mount("#vue-root");

window.addEventListener(
  "pagehide",
  () => {
    reactRoot.unmount();
    vueRoot.unmount();
    void app.dispose();
  },
  { once: true },
);
